# backend:
#   name: git-gateway
#   branch: master
#   commit_messages:
#     create: 'Create {{collection}} “{{slug}}”'
#     update: 'Update {{collection}} “{{slug}}”'
#     delete: 'Delete {{collection}} “{{slug}}”'
#     uploadMedia: '[skip ci] Upload “{{path}}”'
#     deleteMedia: '[skip ci] Delete “{{path}}”'

# ------------------------------- #
# backend:
#   name: proxy
#   proxy_url: http://localhost:8081/api/v1
#   branch: master # optional, defaults to master

# ------------------------------- #
# backend:
#   name: git-gateway

# when using the default proxy server port
# local_backend: true

# local_backend:
#   # when using a custom proxy server port
#   url: http://localhost:8081/api/v1
#   # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
#   allowed_hosts: ['192.168.1.1']


# ------------------------------- #
backend:
  name: github
  branch: master
  repo: walxlgf/poker-web
  base_url: http://192.168.1.99:3000
  auth_endpoint: auth

  
publish_mode: editorial_workflow


media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  
  - name: "series"
    label: "Series"
    folder: "src/pages/series"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Category",
          name: "category",
          widget: "relation",
          collection: "category",
          searchFields: ["title"],
          valueField: "categoryKey",
          multiple: false,
          displayFields: ["title"],
        } 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "series-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Start Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Banner Image", name: "bannerImage", widget: "image"}
      
  - name: "category"
    label: "Category"
    folder: "src/pages/category"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category-page"}
      - {label: "Category Key", name: "categoryKey", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Address", name: "address", widget: "string"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Index"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          # - {
          #     label: "Related Series",
          #     name: "relatedSeries",
          #     widget: "relation",
          #     collection: "series",
          #     searchFields: ["title"],
          #     valueField: "{{slug}}",
          #     multiple: true,
          #     displayFields: ["title"],
          #   } 
          - {label: "Banner Image", name: "bannerImage", widget: "image"}

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
