name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker  install image
      run: docker build -f Dockerfile.install -t poker-web:install .

    - name: Build the Docker  builder image
      run: docker build -f Dockerfile.builder --no-cache  -t poker-web:builder .

    - name: Build the Docker  release image
      run: docker build -f Dockerfile.release --no-cache -t poker-web:v1 .
      
    - name: Remove old container 
      continue-on-error: true
      run: docker container stop poker-web && docker container rm poker-web

    - name: Start new Container
      run: docker run -d --name poker-web -p 80:80 poker-web:v1